[tool.poetry]
name = "web 2-8-1"
version = "0.1.0"
description = ""
authors = ["Red-Roger <144430361+Red-Roger@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
